# Generated by Django 6.0.3 on 2026-03-17 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ebr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deviation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviation_type', models.CharField(choices=[('warning', 'Предупреждение'), ('deviation', 'Отклонение'), ('critical', 'Критическое отклонение')], max_length=20, verbose_name='Тип отклонения')),
                ('parameter_name', models.CharField(max_length=100, verbose_name='Параметр')),
                ('expected_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ожидаемое значение')),
                ('actual_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Фактическое значение')),
                ('tolerance', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Допуск')),
                ('description', models.TextField(verbose_name='Описание')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('action_taken', models.CharField(blank=True, choices=[('block', 'Заблокировать партию'), ('rework', 'Направить на доработку'), ('accept', 'Принять с замечаниями'), ('reject', 'Отклонить партию')], max_length=50, null=True, verbose_name='Принятое действие')),
                ('action_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к действию')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('detected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Обнаружил')),
                ('ebr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebr.ebr', verbose_name='Партия')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_deviations', to=settings.AUTH_USER_MODEL, verbose_name='Решил')),
            ],
            options={
                'verbose_name': 'Отклонение',
                'verbose_name_plural': 'Отклонения',
                'db_table': 'Deviation',
            },
        ),
        migrations.CreateModel(
            name='QCTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('sampling', 'Отбор проб'), ('testing', 'Лабораторные испытания'), ('review', 'Проверка')], max_length=20, verbose_name='Тип задания')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В работе'), ('completed', 'Выполнено'), ('rejected', 'Отклонено')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(verbose_name='Срок выполнения')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qc_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Назначено')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('ebr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebr.ebr', verbose_name='Партия')),
            ],
            options={
                'verbose_name': 'Задание ОКК',
                'verbose_name_plural': 'Задания ОКК',
                'db_table': 'QC_Task',
            },
        ),
        migrations.CreateModel(
            name='QCResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visual_control', models.TextField(verbose_name='Визуальный контроль')),
                ('lab_results', models.TextField(verbose_name='Лабораторные результаты')),
                ('files', models.FileField(blank=True, null=True, upload_to='qc_files/', verbose_name='Прикреплённые файлы')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Предоставил')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quality.qctask', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Результат ОКК',
                'verbose_name_plural': 'Результаты ОКК',
                'db_table': 'QC_Result',
            },
        ),
    ]
