# Generated by Django 6.0.3 on 2026-03-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviation_type', models.CharField(max_length=100, verbose_name='Тип отклонения')),
                ('report_date', models.DateField(verbose_name='Дата отчёта')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% от общего числа')),
                ('main_cause', models.TextField(verbose_name='Основные причины')),
            ],
            options={
                'verbose_name': 'Отчёт по отклонениям',
                'verbose_name_plural': 'Отчёты по отклонениям',
                'unique_together': {('deviation_type', 'report_date')},
            },
        ),
        migrations.CreateModel(
            name='ProductionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Продукт')),
                ('report_date', models.DateField(verbose_name='Дата отчёта')),
                ('batches_count', models.IntegerField(verbose_name='Количество партий')),
                ('units_produced', models.IntegerField(verbose_name='Выпущено единиц')),
                ('defect_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Процент брака')),
                ('raw_material_consumed', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Расход сырья (кг)')),
            ],
            options={
                'verbose_name': 'Отчёт по выпуску',
                'verbose_name_plural': 'Отчёты по выпуску',
                'unique_together': {('product_name', 'report_date')},
            },
        ),
    ]
