# Generated by Django 6.0.3 on 2026-03-16 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MBRStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(choices=[('draft', 'Черновик'), ('approved', 'Утверждён')], max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус MBR',
                'verbose_name_plural': 'Статусы MBR',
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=100, verbose_name='Название параметра')),
                ('unit', models.CharField(max_length=20, verbose_name='Единица измерения')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Значение')),
                ('tolerance', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Допустимое отклонение (%)')),
                ('critical_deviation', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Критическое отклонение (%)')),
            ],
            options={
                'verbose_name': 'Параметр',
                'verbose_name_plural': 'Параметры',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Наименование продукта')),
                ('product_code', models.CharField(max_length=50, unique=True, verbose_name='Код продукта')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=255, verbose_name='Наименование сырья')),
            ],
            options={
                'verbose_name': 'Сырьё',
                'verbose_name_plural': 'Сырьё',
            },
        ),
        migrations.CreateModel(
            name='MBR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10, verbose_name='Версия')),
                ('operations', models.TextField(verbose_name='Описание технологических операций')),
                ('approval_date', models.DateField(blank=True, null=True, verbose_name='Дата утверждения')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Комментарий к версии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_mbrs', to=settings.AUTH_USER_MODEL, verbose_name='Утвердил')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbr.mbrstatus', verbose_name='Статус')),
                ('parameters', models.ManyToManyField(to='mbr.parameter', verbose_name='Параметры процесса')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbr.product', verbose_name='Продукт')),
                ('raw_materials', models.ManyToManyField(to='mbr.rawmaterial', verbose_name='Сырьё')),
            ],
            options={
                'verbose_name': 'MBR (Мастер-рецептура)',
                'verbose_name_plural': 'MBR (Мастер-рецептуры)',
                'unique_together': {('product', 'version')},
            },
        ),
    ]
