# Generated by Django 6.0.3 on 2026-03-16 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mbr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EBRStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(choices=[('in_progress', 'В работе'), ('completed', 'Завершена'), ('blocked', 'Заблокирована')], max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус EBR',
                'verbose_name_plural': 'Статусы EBR',
            },
        ),
        migrations.CreateModel(
            name='EBR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50, unique=True, verbose_name='Номер партии')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала')),
                ('completion_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('inspection_notes', models.TextField(blank=True, null=True, verbose_name='Визуальный контроль и лабораторные испытания')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('actual_parameters', models.ManyToManyField(related_name='ebr_parameters', to='mbr.parameter', verbose_name='Фактические параметры')),
                ('mbr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbr.mbr', verbose_name='MBR')),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_ebrs', to=settings.AUTH_USER_MODEL, verbose_name='Подписал')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebr.ebrstatus', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'EBR (Паспорт партии)',
                'verbose_name_plural': 'EBR (Паспорта партий)',
            },
        ),
    ]
