# Generated by Django 6.0.3 on 2026-03-17 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mbr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EBRStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(choices=[('В работе', 'В работе'), ('Завершена', 'Завершена'), ('Заблокирована', 'Заблокирована')], max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус EBR',
                'verbose_name_plural': 'Статусы EBR',
                'db_table': 'EBR_Status',
            },
        ),
        migrations.CreateModel(
            name='EBR',
            fields=[
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mbr.document')),
                ('batch_number', models.CharField(max_length=50, unique=True, verbose_name='Номер партии')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала')),
                ('completion_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('inspection_notes', models.TextField(blank=True, null=True, verbose_name='Результаты контроля')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('mbr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbr.mbr', verbose_name='Исходный MBR')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator_ebr', to=settings.AUTH_USER_MODEL, verbose_name='Оператор')),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_ebr', to=settings.AUTH_USER_MODEL, verbose_name='Подписал')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebr.ebrstatus', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'EBR',
                'verbose_name_plural': 'EBR',
                'db_table': 'EBR',
            },
        ),
        migrations.CreateModel(
            name='BatchOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_name', models.CharField(max_length=100, verbose_name='Операция')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('in_progress', 'В процессе'), ('completed', 'Завершена'), ('blocked', 'Заблокирована')], default='pending', max_length=20, verbose_name='Статус')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('operator_comment', models.TextField(blank=True, null=True)),
                ('ebr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='ebr.ebr')),
            ],
            options={
                'verbose_name': 'Операция партии',
                'verbose_name_plural': 'Операции партии',
                'db_table': 'Batch_Operation',
            },
        ),
        migrations.CreateModel(
            name='EBRParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Фактическое значение')),
                ('ebr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebr.ebr')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbr.parameter')),
            ],
            options={
                'verbose_name': 'Параметр EBR',
                'verbose_name_plural': 'Параметры EBR',
                'db_table': 'EBR_Parameters',
                'unique_together': {('ebr', 'parameter')},
            },
        ),
    ]
