# Generated by Django 6.0.3 on 2026-04-12 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebrparameter',
            name='critical_deviation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Критическое отклонение (%)'),
        ),
        migrations.AddField(
            model_name='ebrparameter',
            name='max_actual_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Максимальное фактическое значение'),
        ),
        migrations.AddField(
            model_name='ebrparameter',
            name='nominal_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Номинальное значение'),
        ),
        migrations.AddField(
            model_name='ebrparameter',
            name='tolerance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Допустимое отклонение (%)'),
        ),
    ]
