# Generated by Django 6.0.3 on 2026-04-13 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebr', '0002_add_ebr_parameter_fields'),
        ('mbr', '0003_alter_mbrparameter_id_alter_mbrrawmaterial_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebrstatus',
            name='status_name',
            field=models.CharField(choices=[('В ожидании', 'В ожидании'), ('В работе', 'В работе'), ('Завершена', 'Завершена'), ('Заблокирована', 'Заблокирована')], max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='EBRActualParameter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('actual_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Фактическое значение')),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Максимальное значение')),
                ('source', models.CharField(blank=True, choices=[('equipment', 'Оборудование'), ('manual', 'Вручную')], max_length=20, null=True, verbose_name='Источник данных')),
                ('ebr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebr.ebr')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbr.parameter')),
            ],
            options={
                'verbose_name': 'Фактический параметр EBR',
                'verbose_name_plural': 'Фактические параметры EBR',
                'db_table': 'EBR_Actual_Parameters',
                'unique_together': {('ebr', 'parameter')},
            },
        ),
        migrations.CreateModel(
            name='EBRNominalParameter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nominal_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Номинальное значение')),
                ('tolerance_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Допуск (абсолютный)')),
                ('critical_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Критическое отклонение (абсолютное)')),
                ('ebr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebr.ebr')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbr.parameter')),
            ],
            options={
                'verbose_name': 'Номинальный параметр EBR',
                'verbose_name_plural': 'Номинальные параметры EBR',
                'db_table': 'EBR_Nominal_Parameters',
                'unique_together': {('ebr', 'parameter')},
            },
        ),
        migrations.DeleteModel(
            name='EBRParameter',
        ),
    ]
