# Generated by Django 6.0.3 on 2026-04-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebr', '0003_alter_ebrstatus_status_name_ebractualparameter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebr',
            name='pressing_duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Длительность прессования (сек)'),
        ),
        migrations.AddField(
            model_name='ebr',
            name='pressing_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало прессования'),
        ),
    ]
