# Generated by Django 5.2.12 on 2026-03-17 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'db_table': 'Document',
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(choices=[('MBR', 'MBR'), ('EBR', 'EBR')], max_length=50, verbose_name='Тип документа')),
            ],
            options={
                'verbose_name': 'Тип документа',
                'verbose_name_plural': 'Типы документов',
                'db_table': 'Document_Type',
            },
        ),
        migrations.CreateModel(
            name='MBRStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(choices=[('Черновик', 'Черновик'), ('Утверждён', 'Утверждён')], max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус MBR',
                'verbose_name_plural': 'Статусы MBR',
                'db_table': 'MBR_Status',
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=100, verbose_name='Название параметра')),
                ('unit', models.CharField(max_length=20, verbose_name='Единица измерения')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Значение')),
                ('tolerance', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Допустимое отклонение (%)')),
                ('critical_deviation', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Критическое отклонение (%)')),
            ],
            options={
                'verbose_name': 'Параметр',
                'verbose_name_plural': 'Параметры',
                'db_table': 'Parameter',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Наименование продукта')),
                ('product_code', models.CharField(max_length=50, unique=True, verbose_name='Код продукта')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=255, verbose_name='Наименование сырья')),
            ],
            options={
                'verbose_name': 'Сырьё',
                'verbose_name_plural': 'Сырьё',
                'db_table': 'Raw_Material',
            },
        ),
        migrations.CreateModel(
            name='MBR',
            fields=[
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mbr.document')),
                ('version', models.CharField(max_length=10, verbose_name='Версия')),
                ('operations', models.TextField(verbose_name='Технологические операции')),
                ('approval_date', models.DateField(blank=True, null=True, verbose_name='Дата утверждения')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Комментарий к версии')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'MBR',
                'verbose_name_plural': 'MBR',
                'db_table': 'MBR',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbr.documenttype', verbose_name='Тип документа'),
        ),
        migrations.CreateModel(
            name='MBRRawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbr.rawmaterial')),
                ('mbr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbr.mbr')),
            ],
            options={
                'db_table': 'MBR_Raw_Materials',
                'unique_together': {('mbr', 'raw_material')},
            },
        ),
        migrations.CreateModel(
            name='MBRParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbr.parameter')),
                ('mbr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbr.mbr')),
            ],
            options={
                'db_table': 'MBR_Parameters',
                'unique_together': {('mbr', 'parameter')},
            },
        ),
        migrations.AddField(
            model_name='mbr',
            name='parameters',
            field=models.ManyToManyField(through='mbr.MBRParameter', to='mbr.parameter'),
        ),
        migrations.AddField(
            model_name='mbr',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbr.product', verbose_name='Продукт'),
        ),
        migrations.AddField(
            model_name='mbr',
            name='raw_materials',
            field=models.ManyToManyField(through='mbr.MBRRawMaterial', to='mbr.rawmaterial'),
        ),
        migrations.AddField(
            model_name='mbr',
            name='signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Утвердил'),
        ),
        migrations.AddField(
            model_name='mbr',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbr.mbrstatus', verbose_name='Статус'),
        ),
        migrations.AlterUniqueTogether(
            name='mbr',
            unique_together={('product', 'version')},
        ),
    ]
