# Generated by Django 6.0.3 on 2026-04-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbrparameter',
            name='critical_deviation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Критическое отклонение (%)'),
        ),
        migrations.AddField(
            model_name='mbrparameter',
            name='tolerance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Допустимое отклонение (%)'),
        ),
        migrations.AddField(
            model_name='mbrparameter',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Значение'),
        ),
    ]
