# Generated by Django 6.0.3 on 2026-04-10 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbr', '0002_mbrparameter_critical_deviation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbrparameter',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mbrrawmaterial',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
