# Generated by Django 6.0.3 on 2026-03-16 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ebr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('warning', 'Предупреждение'), ('deviation', 'Отклонение'), ('critical', 'Критическое отклонение')], max_length=20, verbose_name='Уровень')),
                ('parameter_name', models.CharField(max_length=100, verbose_name='Параметр')),
                ('actual_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Фактическое значение')),
                ('expected_range', models.CharField(max_length=100, verbose_name='Допустимый диапазон')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='Время обнаружения')),
                ('resolved', models.BooleanField(default=False, verbose_name='Устранено')),
                ('resolution_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('ebr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='ebr.ebr', verbose_name='Партия')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Устранил')),
            ],
            options={
                'verbose_name': 'Оповещение',
                'verbose_name_plural': 'Оповещения',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='QualityTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('sampling', 'Отбор проб'), ('lab_test', 'Лабораторные испытания'), ('visual_check', 'Визуальный контроль')], max_length=20, verbose_name='Тип задания')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В выполнении'), ('completed', 'Выполнено')], default='new', max_length=20, verbose_name='Статус')),
                ('deadline', models.DateTimeField(verbose_name='Срок выполнения')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('result_data', models.TextField(blank=True, null=True, verbose_name='Результаты')),
                ('attached_files', models.FileField(blank=True, null=True, upload_to='quality_files/', verbose_name='Прикреплённые файлы')),
                ('assigned_to', models.ForeignKey(limit_choices_to={'role': 'qc_specialist'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('ebr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_tasks', to='ebr.ebr', verbose_name='Партия')),
            ],
            options={
                'verbose_name': 'Задание ОКК',
                'verbose_name_plural': 'Задания ОКК',
            },
        ),
    ]
