# Generated by Django 6.0.3 on 2026-03-17 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mbr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(max_length=100, verbose_name='Действие')),
            ],
            options={
                'verbose_name': 'Действие',
                'verbose_name_plural': 'Действия',
                'db_table': 'Action',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('audit_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.action', verbose_name='Действие')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mbr.document', verbose_name='Документ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Журнал аудита',
                'db_table': 'Audit_Log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ElectronicSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата подписи')),
                ('signature_hash', models.CharField(max_length=255, verbose_name='Хэш подписи')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbr.document', verbose_name='Документ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Электронная подпись',
                'verbose_name_plural': 'Электронные подписи',
                'db_table': 'Electronic_Signature',
            },
        ),
    ]
