# Generated by Django 5.2.12 on 2026-03-17 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ebr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_units', models.IntegerField(default=0, verbose_name='Выпущено единиц')),
                ('defect_units', models.IntegerField(default=0, verbose_name='Брак (единиц)')),
                ('defect_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Процент брака')),
                ('raw_material_used', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Расход сырья (кг)')),
                ('equipment_efficiency', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Эффективность оборудования (%)')),
                ('ebr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ebr.ebr', verbose_name='Партия')),
            ],
            options={
                'verbose_name': 'Статистика производства',
                'verbose_name_plural': 'Статистика производства',
                'db_table': 'Production_Stats',
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название отчета')),
                ('report_type', models.CharField(choices=[('production', 'Отчет по выпуску продукции'), ('deviation', 'Отчет по отклонениям'), ('efficiency', 'Отчет по эффективности оборудования')], max_length=20, verbose_name='Тип отчета')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Шаблон отчета',
                'verbose_name_plural': 'Шаблоны отчетов',
                'db_table': 'Report_Template',
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата генерации')),
                ('start_date', models.DateField(verbose_name='Начало периода')),
                ('end_date', models.DateField(verbose_name='Конец периода')),
                ('format', models.CharField(choices=[('excel', 'Excel'), ('pdf', 'PDF'), ('csv', 'CSV')], default='excel', max_length=10, verbose_name='Формат')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='Файл отчета')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='Данные отчета')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сгенерировал')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.reporttemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Сгенерированный отчет',
                'verbose_name_plural': 'Сгенерированные отчеты',
                'db_table': 'Generated_Report',
                'ordering': ['-generated_at'],
            },
        ),
    ]
