# Generated by Django 6.0.3 on 2026-04-10 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ebr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PressMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название пресса')),
                ('machine_code', models.CharField(max_length=50, unique=True, verbose_name='Код оборудования')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('last_maintenance', models.DateField(blank=True, null=True, verbose_name='Последнее ТО')),
            ],
            options={
                'verbose_name': 'Таблеточный пресс',
                'verbose_name_plural': 'Таблеточные прессы',
                'db_table': 'Press_Machine',
            },
        ),
        migrations.CreateModel(
            name='EquipmentReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время считывания')),
                ('pressure_force', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Усилие прессования (кН)')),
                ('tablet_thickness', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Толщина таблетки (мм)')),
                ('tablet_weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Масса таблетки (мг)')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ebr.ebr', verbose_name='Партия')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.pressmachine', verbose_name='Пресс')),
            ],
            options={
                'verbose_name': 'Показания оборудования',
                'verbose_name_plural': 'Показания оборудования',
                'db_table': 'Equipment_Readings',
                'ordering': ['-timestamp'],
            },
        ),
    ]
